# 开发环境配置
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testmongodb

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 692924154089-9jrsn9udb21t8158hvdrmk2q8vpt8g59.apps.googleusercontent.com
            client-secret: M-dCKT74Fm4XvLj-rlnyKaez



